import fs from 'node:fs';
const input=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const universalBase=function(...args){return universal};
const universal=new Proxy(universalBase,{get(t,p){if(p==='then')return undefined;if(p===Symbol.toPrimitive)return ()=>'';if(p==='toString')return ()=> '[object Object]';let v=Reflect.get(t,p);return v===undefined?universal:typeof v==='function'?v.bind(t):v},apply(){return universal}});
const proxyObj=(obj)=>new Proxy(obj,{get(t,p,r){if(p in t){return Reflect.get(t,p,r)}if(p==='then')return undefined;if(p===Symbol.toPrimitive)return ()=> '[object Object]';return universal}});
const fakeStorage=new Map();
const localStorage=proxyObj({getItem:k=>fakeStorage.get(String(k))??null,setItem:(k,v)=>fakeStorage.set(String(k),String(v)),removeItem:k=>fakeStorage.delete(String(k)),clear:()=>fakeStorage.clear(),key:i=>[...fakeStorage.keys()][i]??null,get length(){return fakeStorage.size}});
const body=proxyObj({});
const documentElement=proxyObj({getAttribute:k=>k==='data-build'?'prod-test':null});
const document=proxyObj({scripts:[],body,documentElement,location:null});
const navigator=proxyObj({userAgent:'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36',language:'zh-CN',languages:['zh-CN','zh'],hardwareConcurrency:12,webdriver:false,onLine:true,platform:'Win32',maxTouchPoints:0,cookieEnabled:true});
const screen=proxyObj({width:1920,height:1080,availWidth:1920,availHeight:1040,colorDepth:24,pixelDepth:24});
const history=proxyObj({length:1,state:null,scrollRestoration:'auto'});
const location=proxyObj({href:'https://chatgpt.com/',origin:'https://chatgpt.com',hostname:'chatgpt.com',protocol:'https:',pathname:'/',search:'',hash:'',toString(){return this.href}});
document.location=location;
const windowBase={Reflect,Object,Math,JSON,Array,String,Number,Boolean,Date,Promise,RegExp,Error,TypeError,Map,Set,WeakMap,performance,localStorage,document,navigator,screen,history,location,crypto:globalThis.crypto,atob,btoa,setTimeout,clearTimeout};
const windowObj=proxyObj(windowBase);windowBase.window=windowObj;windowBase.self=windowObj;windowBase.globalThis=windowObj;
Object.defineProperties(globalThis,{window:{value:windowObj,configurable:true},document:{value:document,configurable:true},navigator:{value:navigator,configurable:true},screen:{value:screen,configurable:true},history:{value:history,configurable:true},location:{value:location,configurable:true},localStorage:{value:localStorage,configurable:true}});var n=0,r=1,i=2,a=3,o=4,s=5,c=6,l=24,u=7,d=8,f=9,p=10,m=11,h=12,g=13,_=14,v=15,y=16,b=17,x=18,S=19,C=23,w=20,T=21,E=22,D=25,O=26,k=27,A=28,j=29,M=30,N=33,P=34,F=35,I=new Map,L=0,R=Promise.resolve();
function z(e){let t=R.then(e,e);return R=t.then(()=>void 0,()=>void 0),t}
async function B(){for(;I.get(f).length>0;){let instr=I.get(f)[0];let[e,...t]=I.get(f).shift();try{let n=I.get(e)(...t);n&&typeof n.then==='function'&&await n;L++}catch(err){throw new Error('VM L='+L+' instr='+JSON.stringify(instr)+' vals='+t.map(x=>{let v=I.get(x);return x+':'+typeof v+':'+String(v).slice(0,80)}).join('|')+' :: '+err)}}}
function V(e){return z(()=>new Promise((t,n)=>{let r=!1;setTimeout(()=>{r=!0,t(''+L)},500),I.set(a,e=>{r||(r=!0,t(btoa(''+e)))}),I.set(o,e=>{r||(r=!0,n(btoa(''+e)))}),I.set(M,(e,t,n,i)=>{let a=Array.isArray(i),o=a?n:[],s=(a?i:n)||[];I.set(e,(...e)=>{if(r)return;let n=[...I.get(f)];if(a)for(let t=0;t<o.length;t++){let n=o[t],r=e[t];I.set(n,r)}return I.set(f,[...s]),B().then(()=>I.get(t)).catch(e=>''+e).finally(()=>{I.set(f,n)})})});try{I.set(f,JSON.parse(U(atob(e),''+I.get(y)))),B().catch(e=>{t(btoa(L+': '+e))})}catch(e){t(btoa(L+': '+e))}}))}
function H(key,dx){return z(()=>new Promise((r,i)=>{let s=key??'';W(),L=0,I.set(y,s);let c=!1;setTimeout(()=>{c=!0,r(''+L)},500),I.set(a,e=>{c||(c=!0,r(btoa(''+e)))}),I.set(o,e=>{c||(c=!0,i(btoa(''+e)))}),I.set(M,(e,t,n,r)=>{let i=Array.isArray(r),a=i?n:[],o=(i?r:n)||[];I.set(e,(...e)=>{if(c)return;let n=[...I.get(f)];if(i)for(let t=0;t<a.length;t++){let n=a[t],r=e[t];I.set(n,r)}return I.set(f,[...o]),B().then(()=>I.get(t)).catch(e=>''+e).finally(()=>{I.set(f,n)})})});try{I.set(f,JSON.parse(U(atob(dx),''+I.get(y)))),B().catch(e=>{r(btoa(L+': '+e))})}catch(e){r(btoa(L+': '+e))}}))}
function U(e,t){let n='';for(let r=0;r<e.length;r++)n+=String.fromCharCode(e.charCodeAt(r)^t.charCodeAt(r%t.length));return n}
function W(){I.clear(),I.set(n,V),I.set(r,(e,t)=>I.set(e,U(''+I.get(e),''+I.get(t)))),I.set(i,(e,t)=>I.set(e,t)),I.set(s,(e,t)=>{let n=I.get(e);Array.isArray(n)?n.push(I.get(t)):I.set(e,n+I.get(t))}),I.set(k,(e,t)=>{let n=I.get(e);Array.isArray(n)?n.splice(n.indexOf(I.get(t)),1):I.set(e,n-I.get(t))}),I.set(j,(e,t,n)=>I.set(e,I.get(t)<I.get(n))),I.set(N,(e,t,n)=>{let r=Number(I.get(t)),i=Number(I.get(n));I.set(e,r*i)}),I.set(F,(e,t,n)=>{let r=Number(I.get(t)),i=Number(I.get(n));I.set(e,i===0?0:r/i)}),I.set(c,(e,t,n)=>I.set(e,I.get(t)[I.get(n)])),I.set(u,(e,...t)=>I.get(e)(...t.map(e=>I.get(e)))),I.set(b,(e,t,...n)=>{try{let r=I.get(t)(...n.map(e=>I.get(e)));if(r&&typeof r.then==='function')return r.then(t=>{I.set(e,t)}).catch(t=>{I.set(e,''+t)});I.set(e,r)}catch(t){console.error('TRYCALL_FAIL',e,t,n.map(x=>[x,typeof I.get(x),String(I.get(x)).slice(0,100)]));I.set(e,''+t)}}),I.set(g,(e,t,...n)=>{try{I.get(t)(...n)}catch(t){I.set(e,''+t)}}),I.set(d,(e,t)=>I.set(e,I.get(t))),I.set(p,windowObj),I.set(m,(e,t)=>I.set(e,(Array.from(document.scripts||[]).map(e=>e?.src?.match(I.get(t))).filter(e=>e?.length)[0]??[])[0]??null)),I.set(h,e=>I.set(e,I)),I.set(_,(e,t)=>I.set(e,JSON.parse(''+I.get(t)))),I.set(v,(e,t)=>I.set(e,JSON.stringify(I.get(t)))),I.set(x,e=>I.set(e,atob(''+I.get(e)))),I.set(S,e=>I.set(e,btoa(''+I.get(e)))),I.set(w,(e,t,n,...r)=>I.get(e)===I.get(t)?I.get(n)(...r):null),I.set(T,(e,t,n,r,...i)=>Math.abs(I.get(e)-I.get(t))>I.get(n)?I.get(r)(...i):null),I.set(C,(e,t,...n)=>I.get(e)===void 0?null:I.get(t)(...n)),I.set(l,(e,t,n)=>I.set(e,I.get(t)[I.get(n)].bind(I.get(t)))),I.set(P,(e,t)=>{try{let n=I.get(t);return Promise.resolve(n).then(t=>{I.set(e,t)})}catch{return}}),I.set(E,(e,t)=>{let n=[...I.get(f)];return I.set(f,[...t]),B().catch(t=>{I.set(e,''+t)}).finally(()=>{I.set(f,n)})}),I.set(A,()=>{}),I.set(O,()=>{}),I.set(D,()=>{})}
const out=await H(input.p,input.dx);console.log(JSON.stringify({out,len:out.length,L,decoded: (()=>{try{return atob(out)}catch{return null}})()}));






